from enum import StrEnum

class AgentType(StrEnum):
    DOCTOR = 'DOCTOR'
    NURSE = 'NURSE'
    PHYSIOTHERAPIST = 'PHYSIOTHERAPIST'
    NUTRITIONIST = 'NUTRITIONIST'
    DIALYSIS_TECHNICIAN = 'DIALYSIS_TECHNICIAN'
    CHEMOTHERAPY_TECHNICIAN = 'CHEMOTHERAPY_TECHNICIAN'
    RADIOTHERAPY_TECHNICIAN = 'RADIOTHERAPY_TECHNICIAN'
    REHABILITATION_SPECIALIST = 'REHABILITATION_SPECIALIST'
    OTHER = 'OTHER'