from enum import StrEnum

class ProcedureType(StrEnum):
    PHYSIOTHERAPY = 'PHYSIOTHERAPY'
    NUTRITIONAL_THERAPY = 'NUTRITIONAL_THERAPY'
    HEMODIALYSIS = 'HEMODIALYSIS'
    CHEMOTHERAPY = 'CHEMOTHERAPY'
    RADIOTHERAPY = 'RADIOTHERAPY'
    PHYSICAL_REHABILITATION = 'PHYSICAL_REHABILITATION'
    OTHER = 'OTHER' 